server {
    listen 3081;
    server_name _;
    # 当启用 dsh 缓存时，加上这个，允许 openresty 在 dsh-env:3080 无法接通时启动
    set $backend_url http://dsh-env:3080;
    location / {
        proxy_pass $backend_url;
        # 若你没有配置认证插件， dsh 不接受外部连接
        # proxy_set_header Host localhost:3080;
        # proxy_set_header Origin http://localhost:3080;
        # proxy_set_header X-Real-IP $remote_addr;
        # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # 别忘了这个，不然 dsh 的提问会被 websocket 断开所打断
        # 代理超时设置
        proxy_read_timeout 3600s; # 或直接 0（不限）
        proxy_send_timeout 3600s;
    }

    error_page 404 @error_404;

    location @error_404 {

        default_type text/html;

        return 404 '
        <!DOCTYPE html>
        <html>
        <head><meta charset="UTF-8"><title>dsh</title></head>
        <body>
        <h1>404</h1>
        <p>Not Found</p>
        </body>
        </html>
        ';
    }
}