server {
    listen 3080;
    server_name _;
    set $backend_url http://dsh-env:3080;
    location / {
        proxy_pass $backend_url;
        # 认证用
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        # WebSocket 必需
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 3600s; # 或直接 0（不限）
        proxy_send_timeout 3600s;
    }
    error_page 404 @error_404;

    location @error_404 {
        default_type text/html;
        return 404 '
        <!DOCTYPE html>
        <html>
        <head><meta charset="UTF-8"><title>404</title></head>
        <body>
        <h1>404</h1>
        <p>lts</p>
        </body>
        </html>
        ';
    }
}