FROM node:26.10.0-bookworm-slim

RUN --mount=type=cache,target=/var/cache/apt \
    --mount=type=cache,target=/var/lib/apt \
    apt-get update && apt-get install -y \
    # 标准工具组
    git curl wget vim procps \
    build-essential \
    # python 工具组
    python3 python3-pip python3-venv \
    # dsh 安全策略要求一个沙箱才能运行bash：
    bubblewrap \
    # ssh 工具
    openssh-server \
    # nginx 服务
    # nginx \
    # 无头浏览器截图核心组件
    chromium-headless-shell \
    # 无头 Chromium 运行时依赖库
    libnspr4 libnss3 libexpat1 libfontconfig1 \
    # 基础字体（保证英文正常渲染）
    fonts-liberation \
    # 中文字体（按需，保证中文正常渲染）
    fonts-wqy-zenhei \
    && rm -rf /var/lib/apt/lists/* \
    # && test -f /usr/sbin/nginx \
    && test -f /usr/sbin/sshd

RUN ln -s /usr/bin/python3 /usr/bin/python
RUN npm install -g pnpm

# 确保 ssh 服务目录存在
RUN mkdir -p /run/sshd && \
    chmod 0755 /run/sshd && \
    chown root:root /run/sshd

# 设置环境变量，让 Puppeteer/Playwright 找到系统安装的无头浏览器
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-headless-shell \
    CHROME_BIN=/usr/bin/chromium-headless-shell

WORKDIR /app